import type { ProductPreview, StorePreview } from './types';

type DemoCatalogAssets = {
  themedImage: (categorySlug: string, index: number) => string;
  heroImage: string;
  categoryImageFallback: string;
};

export function createDemoCatalog({
  themedImage,
  heroImage,
  categoryImageFallback,
}: DemoCatalogAssets) {
  const products: ProductPreview[] = [
    {
      slug: 'kis-qis-godekceleri-model-402',
      title: 'Kişi qış gödəkçələri Model 402',
      store: 'Baku Tekstil MMC',
      storeSlug: 'baku-tekstil-mmc',
      city: 'Bakı',
      category: 'Geyim və Tekstil',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: 'Razılaşma yolu ilə',
      minOrder: 'Min: 50 ədəd',
      badge: 'Yeni',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 0),
      imageAlt: 'Topdansatış geyim məhsulları',
      whatsappNumber: '+994501234567',
      phone: '+994501234567',
    },
    {
      slug: 'qadin-deri-cekmeleri-stok-500-cut',
      title: 'Qadın dəri çəkmələri Stok 500 cüt',
      store: 'Shoes Import Trade',
      storeSlug: 'shoes-import-trade',
      city: 'Sumqayıt',
      category: 'Ayaqqabı',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: 'Razılaşma yolu ilə',
      minOrder: 'Min: 100 cüt',
      badge: 'Stokda var',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 1),
      imageAlt: 'Topdansatış ayaqqabı məhsulları',
      whatsappNumber: '+994552223344',
      phone: '+994552223344',
    },
    {
      slug: 'agilli-saatlar-x-series',
      title: 'Ağıllı saatlar X-Series Minimum sifariş 50',
      store: 'TechWholesale AZ',
      storeSlug: 'techwholesale-az',
      city: 'Bakı',
      category: 'Elektronika',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: 'Razılaşma yolu ilə',
      minOrder: 'Min: 50 ədəd',
      badge: 'Top satıcı',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 2),
      imageAlt: 'Topdansatış ağıllı saat məhsulları',
      whatsappNumber: '+994551112233',
      phone: '+994551112233',
    },
    {
      slug: 'akkumulyatorlu-drel-desti',
      title: 'Akkumulyatorlu drel dəsti Topdan satış',
      store: 'Mega İnşaat Supply',
      storeSlug: 'mega-insaat-supply',
      city: 'Gəncə',
      category: 'Təmir və tikinti',
      categorySlug: 'tikinti-ve-temir',
      price: 'Razılaşma yolu ilə',
      minOrder: 'Min: 20 ədəd',
      badge: 'Yeni partiya',
      imageUrl: themedImage('tikinti-ve-temir', 3),
      imageAlt: 'Topdansatış elektrik alətləri',
      whatsappNumber: '+994703334455',
      phone: '+994703334455',
    },
  ];

  const stores: StorePreview[] = [
    {
      slug: 'baku-tekstil-mmc',
      name: 'Baku Tekstil MMC',
      category: 'Geyim və Tekstil',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      productCount: '1,250+',
      city: 'Bakı',
      views: '12.5K',
      coverImageUrl: heroImage,
      description:
        'Baku Tekstil MMC Azərbaycanda topdansatış geyim və tekstil məhsulları üzrə işləyən yoxlanılmış təchizatçılardan biridir.',
      verified: true,
      phone: '+994501234567',
      whatsappNumber: '+994501234567',
    },
    {
      slug: 'shoes-import-trade',
      name: 'Shoes Import Trade',
      category: 'Ayaqqabı və dəri məmulatları',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      productCount: '840+',
      city: 'Sumqayıt',
      views: '8.2K',
      coverImageUrl: categoryImageFallback,
      description: 'Shoes Import Trade topdan ayaqqabı və dəri məmulatları təklif edir.',
      verified: true,
      phone: '+994552223344',
      whatsappNumber: '+994552223344',
    },
    {
      slug: 'techwholesale-az',
      name: 'TechWholesale AZ',
      category: 'Elektronika və aksesuarlar',
      categorySlug: 'elektronika-ve-aksesuarlar',
      productCount: '3,100+',
      city: 'Bakı',
      views: '21.4K',
      coverImageUrl: categoryImageFallback,
      description:
        'TechWholesale AZ elektronika və aksesuarların topdansatış təchizatı üçün biznes alıcılarla işləyir.',
      verified: true,
      phone: '+994551112233',
      whatsappNumber: '+994551112233',
    },
  ];

  stores.push(
    {
      slug: 'absheron-food-supply',
      name: 'Absheron Food Supply',
      category: 'Qida və içki',
      categorySlug: 'qida-ve-icki',
      productCount: '4',
      city: 'Bakı',
      views: 'Yeni',
      coverImageUrl: categoryImageFallback,
      description: 'Market, restoran və kafe şəbəkələri üçün qida və içki topdan satışı.',
      verified: true,
      phone: '+994502101010',
      whatsappNumber: '+994502101010',
    },
    {
      slug: 'caspian-electro-hub',
      name: 'Caspian Electro Hub',
      category: 'Elektronika və aksesuarlar',
      categorySlug: 'elektronika-ve-aksesuarlar',
      productCount: '4',
      city: 'Bakı',
      views: 'Yeni',
      coverImageUrl: categoryImageFallback,
      description: 'Telefon aksesuarları, smart cihazlar və ofis texnikası üzrə topdan təklif.',
      verified: true,
      phone: '+994552202020',
      whatsappNumber: '+994552202020',
    },
    {
      slug: 'probuild-materials',
      name: 'ProBuild Materials',
      category: 'Tikinti və təmir',
      categorySlug: 'tikinti-ve-temir',
      productCount: '4',
      city: 'Gəncə',
      views: 'Yeni',
      coverImageUrl: heroImage,
      description:
        'Tikinti briqadaları və obyektlər üçün material, boya və elektrik ləvazimatları.',
      verified: true,
      phone: '+994773404040',
      whatsappNumber: '+994773404040',
    },
    {
      slug: 'packline-print',
      name: 'PackLine Print',
      category: 'Qablaşdırma və reklam məhsulları',
      categorySlug: 'qablasdirma-ve-reklam-mehsullari',
      productCount: '4',
      city: 'Bakı',
      views: 'Yeni',
      coverImageUrl: categoryImageFallback,
      description: 'Brendli qablaşdırma, promo məhsullar və çap xidmətləri.',
      verified: true,
      phone: '+994508808080',
      whatsappNumber: '+994508808080',
    },
    {
      slug: 'agroline-b2b',
      name: 'AgroLine B2B',
      category: 'Kənd təsərrüfatı və heyvandarlıq',
      categorySlug: 'kend-teserrufati-ve-heyvandarliq',
      productCount: '4',
      city: 'Mingəçevir',
      views: 'Yeni',
      coverImageUrl: heroImage,
      description: 'Fermerlər və təsərrüfatlar üçün toxum, gübrə, yem və avadanlıq.',
      verified: true,
      phone: '+994559909090',
      whatsappNumber: '+994559909090',
    },
  );

  products.push(
    {
      slug: 'premium-un-50kg-paleti',
      title: 'Premium un 50 kq palet',
      store: 'Absheron Food Supply',
      storeSlug: 'absheron-food-supply',
      city: 'Bakı',
      category: 'Un, şəkər və duz',
      categorySlug: 'un-seker-ve-duz',
      price: '32 AZN',
      minOrder: 'Min: 20 paket',
      badge: 'Stokda var',
      imageUrl: themedImage('un-seker-ve-duz', 0),
      imageAlt: 'Topdan ərzaq məhsulu',
      whatsappNumber: '+994502101010',
      phone: '+994502101010',
    },
    {
      slug: 'qazli-icki-mix-24-lu-qutu',
      title: 'Qazlı içki mix 24-lü qutu',
      store: 'Absheron Food Supply',
      storeSlug: 'absheron-food-supply',
      city: 'Bakı',
      category: 'Şirələr və qazlı içkilər',
      categorySlug: 'sireler-ve-qazli-ickiler',
      price: '18.40 AZN',
      minOrder: 'Min: 30 qutu',
      badge: 'Yeni',
      imageUrl: themedImage('sireler-ve-qazli-ickiler', 1),
      imageAlt: 'Topdan içki məhsulu',
      whatsappNumber: '+994502101010',
      phone: '+994502101010',
    },
    {
      slug: 'usb-c-kabel-100-ededlik-paket',
      title: 'USB-C kabel 100 ədədlik paket',
      store: 'Caspian Electro Hub',
      storeSlug: 'caspian-electro-hub',
      city: 'Bakı',
      category: 'Adapter və kabellər',
      categorySlug: 'adapter-ve-kabeller',
      price: '145 AZN',
      minOrder: 'Min: 5 paket',
      badge: 'Top satıcı',
      imageUrl: themedImage('adapter-ve-kabeller', 2),
      imageAlt: 'Topdan elektronika aksesuarı',
      whatsappNumber: '+994552202020',
      phone: '+994552202020',
    },
    {
      slug: 'powerbank-10000mah-topdan-partiya',
      title: 'Powerbank 10000mAh topdan partiya',
      store: 'Caspian Electro Hub',
      storeSlug: 'caspian-electro-hub',
      city: 'Bakı',
      category: 'Powerbanklar',
      categorySlug: 'powerbanklar',
      price: 'Razılaşma yolu ilə',
      minOrder: 'Min: 50 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('powerbanklar', 3),
      imageAlt: 'Topdan powerbank məhsulu',
      whatsappNumber: '+994552202020',
      phone: '+994552202020',
    },
    {
      slug: 'sement-m500-50kg-topdan',
      title: 'Sement M500 50 kq topdan',
      store: 'ProBuild Materials',
      storeSlug: 'probuild-materials',
      city: 'Gəncə',
      category: 'Sement və qum',
      categorySlug: 'sement-ve-qum',
      price: '9.20 AZN',
      minOrder: 'Min: 120 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('sement-ve-qum', 0),
      imageAlt: 'Topdan tikinti materialı',
      whatsappNumber: '+994773404040',
      phone: '+994773404040',
    },
    {
      slug: 'karton-qutu-40x30x30-500-eded',
      title: 'Karton qutu 40x30x30 500 ədəd',
      store: 'PackLine Print',
      storeSlug: 'packline-print',
      city: 'Bakı',
      category: 'Karton qutular',
      categorySlug: 'karton-qutular',
      price: '0.72 AZN',
      minOrder: 'Min: 500 ədəd',
      badge: 'Yeni',
      imageUrl: themedImage('karton-qutular', 1),
      imageAlt: 'Topdan qablaşdırma məhsulu',
      whatsappNumber: '+994508808080',
      phone: '+994508808080',
    },
    {
      slug: 'mineral-gubre-25kg-topdan',
      title: 'Mineral gübrə 25 kq topdan',
      store: 'AgroLine B2B',
      storeSlug: 'agroline-b2b',
      city: 'Mingəçevir',
      category: 'Mineral gübrələr',
      categorySlug: 'mineral-gubreler',
      price: '17.50 AZN',
      minOrder: 'Min: 80 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('mineral-gubreler', 2),
      imageAlt: 'Topdan kənd təsərrüfatı məhsulu',
      whatsappNumber: '+994559909090',
      phone: '+994559909090',
    },
  );

  stores.push(
    {
      slug: 'sumqayit-tekstil-emal',
      name: 'Sumqayıt Tekstil Emalı',
      category: 'Geyim və Tekstil',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      productCount: '620+',
      city: 'Sumqayıt',
      views: '5.1K',
      coverImageUrl: categoryImageFallback,
      description:
        'Topdan kösələk, köynək və trikotaj partiyaları. Podyom və butiklər üçün təchizat.',
      verified: true,
      phone: '+994556667788',
      whatsappNumber: '+994556667788',
    },
    {
      slug: 'ganca-market-techizati',
      name: 'Gəncə Market Təchizatı',
      category: 'Qida və içki',
      categorySlug: 'qida-ve-icki',
      productCount: '1,100+',
      city: 'Gəncə',
      views: '7.8K',
      coverImageUrl: heroImage,
      description: 'Market və univermaq şəbəkələri üçün ərzaq, şirniyyat və içki topdan satışı.',
      verified: true,
      phone: '+994553334455',
      whatsappNumber: '+994553334455',
    },
    {
      slug: 'baku-elektronik-bazari',
      name: 'Bakı Elektronik Bazarı',
      category: 'Elektronika və aksesuarlar',
      categorySlug: 'elektronika-ve-aksesuarlar',
      productCount: '2,400+',
      city: 'Bakı',
      views: '15.2K',
      coverImageUrl: heroImage,
      description: 'Telefon aksesuarları, audio və kiçik texnika üzrə topdan partiyalar.',
      verified: true,
      phone: '+994704445566',
      whatsappNumber: '+994704445566',
    },
    {
      slug: 'sheki-bal-mehsullari',
      name: 'Şəki Bal Məhsulları',
      category: 'Qida və içki',
      categorySlug: 'qida-ve-icki',
      productCount: '320+',
      city: 'Şəki',
      views: '6.1K',
      coverImageUrl: categoryImageFallback,
      description:
        'Təbii bal, qoz və region məhsullarının topdan satışı. Butik marketlər üçün xüsusi qablaşdırma.',
      verified: true,
      phone: '+994771112233',
      whatsappNumber: '+994771112233',
    },
    {
      slug: 'lenkeran-meyve-emali',
      name: 'Lənkəran Meyvə Emalı',
      category: 'Qida və içki',
      categorySlug: 'qida-ve-icki',
      productCount: '580+',
      city: 'Lənkəran',
      views: '5.4K',
      coverImageUrl: categoryImageFallback,
      description: 'Sitrus, konserv və şirə partiyaları. Market şəbəkələri ilə birbaşa əməkdaşlıq.',
      verified: true,
      phone: '+994772223344',
      whatsappNumber: '+994772223344',
    },
    {
      slug: 'quba-xalca-ve-suvenir',
      name: 'Quba Xalça və Suvenir',
      category: 'Ev və bağ',
      categorySlug: 'ev-ve-bag',
      productCount: '410+',
      city: 'Quba',
      views: '3.9K',
      coverImageUrl: categoryImageFallback,
      description: 'Xalça, ev tekstili və suvenir məhsullarının topdan təchizatı.',
      verified: true,
      phone: '+994773334455',
      whatsappNumber: '+994773334455',
    },
    {
      slug: 'mingecevir-mebel-topdan',
      name: 'Mingəçevir Mebel Topdan',
      category: 'Ev və bağ',
      categorySlug: 'ev-ve-bag',
      productCount: '690+',
      city: 'Mingəçevir',
      views: '4.7K',
      coverImageUrl: categoryImageFallback,
      description:
        'Ofis və ev mebellərinin topdan satışı. Mebel mağazaları üçün partiya təklifləri.',
      verified: true,
      phone: '+994774445566',
      whatsappNumber: '+994774445566',
    },
    {
      slug: 'zaqatala-qeyri-mehsullar',
      name: 'Zaqatala Qeyri-Məhsulları',
      category: 'Qida və içki',
      categorySlug: 'qida-ve-icki',
      productCount: '240+',
      city: 'Zaqatala',
      views: 'Yeni',
      coverImageUrl: categoryImageFallback,
      description: 'Qoz, fındıq və quru meyvə partiyaları. Bu həftə bazara qoşuldu.',
      verified: true,
      phone: '+994775556677',
      whatsappNumber: '+994775556677',
    },
    {
      slug: 'abseron-qab-qacaq',
      name: 'Abşeron Qab-Qacaq Topdan',
      category: 'Ev və bağ',
      categorySlug: 'ev-ve-bag',
      productCount: '1,050+',
      city: 'Bakı',
      views: '9.3K',
      coverImageUrl: categoryImageFallback,
      description: 'Mətbəx ləvazimatı, plastik və şüşə qabların topdan satışı.',
      verified: true,
      phone: '+994776667788',
      whatsappNumber: '+994776667788',
    },
    {
      slug: 'salyan-teserrufat-mallari',
      name: 'Salyan Təsərrüfat Malları',
      category: 'Təmir və tikinti',
      categorySlug: 'tikinti-ve-temir',
      productCount: '380+',
      city: 'Mingəçevir',
      views: 'Yeni',
      coverImageUrl: categoryImageFallback,
      description: 'Bağ-bostan alətləri, təsərrüfat malları və inşaat materialları topdan.',
      verified: true,
      phone: '+994777778899',
      whatsappNumber: '+994777778899',
    },
  );

  products.push(
    {
      slug: 'pambiq-corab-mix-500-cut',
      title: 'Pambıq corab mix 500 cüt partiya',
      store: 'Baku Tekstil MMC',
      storeSlug: 'baku-tekstil-mmc',
      city: 'Bakı',
      category: 'Corab və trikotaj',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '0.85 AZN',
      priceTiers: [
        { qty: '500+ cüt', price: '0.85 AZN' },
        { qty: '2000+ cüt', price: '0.74 AZN' },
        { qty: '5000+ cüt', price: '0.65 AZN' },
      ],
      minOrder: 'Min: 500 cüt',
      badge: 'Stokda var',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 1),
      imageAlt: 'Topdan corab məhsulu',
      whatsappNumber: '+994501234567',
      phone: '+994501234567',
    },
    {
      slug: 'usaq-idman-ayaqqabisi-200-cut',
      title: 'Uşaq idman ayaqqabısı 200 cüt partiya',
      store: 'Shoes Import Trade',
      storeSlug: 'shoes-import-trade',
      city: 'Sumqayıt',
      category: 'Uşaq ayaqqabıları',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '6.40 AZN',
      priceTiers: [
        { qty: '200+ cüt', price: '6.40 AZN' },
        { qty: '500+ cüt', price: '5.80 AZN' },
      ],
      minOrder: 'Min: 200 cüt',
      badge: 'Yeni partiya',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 2),
      imageAlt: 'Topdan uşaq ayaqqabısı',
      whatsappNumber: '+994552223344',
      phone: '+994552223344',
    },
    {
      slug: 'bluetooth-qulaqliq-300-eded',
      title: 'Bluetooth qulaqlıq 300 ədəd topdan',
      store: 'TechWholesale AZ',
      storeSlug: 'techwholesale-az',
      city: 'Bakı',
      category: 'Audio avadanlıqlar',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: '4.90 AZN',
      priceTiers: [
        { qty: '300+ ədəd', price: '4.90 AZN' },
        { qty: '1000+ ədəd', price: '4.20 AZN' },
      ],
      minOrder: 'Min: 300 ədəd',
      badge: 'Top satıcı',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 0),
      imageAlt: 'Topdan bluetooth qulaqlıq',
      whatsappNumber: '+994551112233',
      phone: '+994551112233',
    },
    {
      slug: 'boyada-desti-50-eded-topdan',
      title: 'Boya dəsti 50 ədəd topdan partiya',
      store: 'Mega İnşaat Supply',
      storeSlug: 'mega-insaat-supply',
      city: 'Gəncə',
      category: 'Boya və ləvazimat',
      categorySlug: 'tikinti-ve-temir',
      price: '12 AZN',
      priceTiers: [
        { qty: '50+ dəst', price: '12 AZN' },
        { qty: '200+ dəst', price: '10.50 AZN' },
      ],
      minOrder: 'Min: 50 dəst',
      badge: 'Stokda var',
      imageUrl: themedImage('tikinti-ve-temir', 3),
      imageAlt: 'Topdan boya dəsti',
      whatsappNumber: '+994703334455',
      phone: '+994703334455',
    },
    {
      slug: 'cay-yarpagi-5kq-qutu',
      title: 'Çay yarpağı 5 kq topdan qutu',
      store: 'Absheron Food Supply',
      storeSlug: 'absheron-food-supply',
      city: 'Bakı',
      category: 'Çay və qəhvə',
      categorySlug: 'sireler-ve-qazli-ickiler',
      price: '28 AZN',
      priceTiers: [
        { qty: '40+ qutu', price: '28 AZN' },
        { qty: '100+ qutu', price: '25 AZN' },
      ],
      minOrder: 'Min: 40 qutu',
      badge: 'Yeni',
      imageUrl: themedImage('sireler-ve-qazli-ickiler', 2),
      imageAlt: 'Topdan çay məhsulu',
      whatsappNumber: '+994502101010',
      phone: '+994502101010',
    },
  );

  products.push(
    {
      slug: 'kisi-koselek-partiya-300-ed',
      title: 'Kişi kösələk partiya 300 ədəd',
      store: 'Sumqayıt Tekstil Emalı',
      storeSlug: 'sumqayit-tekstil-emal',
      city: 'Sumqayıt',
      category: 'Kişi geyimləri',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '9.50 AZN',
      minOrder: 'Min: 300 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 0),
      imageAlt: 'Topdan kişi kösələk partiyası',
      whatsappNumber: '+994556667788',
      phone: '+994556667788',
    },
    {
      slug: 'usaq-pambiq-koynekleri-150-ed',
      title: 'Uşaq pambıq köynəkləri 150 ədəd',
      store: 'Sumqayıt Tekstil Emalı',
      storeSlug: 'sumqayit-tekstil-emal',
      city: 'Sumqayıt',
      category: 'Uşaq geyimləri',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '4.20 AZN',
      priceTiers: [
        { qty: '150+ ədəd', price: '4.20 AZN' },
        { qty: '500+ ədəd', price: '3.75 AZN' },
      ],
      minOrder: 'Min: 150 ədəd',
      badge: 'Yeni partiya',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 2),
      imageAlt: 'Topdan uşaq köynək partiyası',
      whatsappNumber: '+994556667788',
      phone: '+994556667788',
    },
    {
      slug: 'topdan-sokolad-mix-20kq',
      title: 'Topdan şokolad mix 20 kq qutu',
      store: 'Gəncə Market Təchizatı',
      storeSlug: 'ganca-market-techizati',
      city: 'Gəncə',
      category: 'Şokolad və konfetlər',
      categorySlug: 'qida-ve-icki',
      price: '52 AZN',
      priceTiers: [
        { qty: '20+ qutu', price: '52 AZN' },
        { qty: '60+ qutu', price: '47 AZN' },
      ],
      minOrder: 'Min: 20 qutu',
      badge: 'Top satıcı',
      imageUrl: themedImage('qida-ve-icki', 1),
      imageAlt: 'Topdan şokolad partiyası',
      whatsappNumber: '+994553334455',
      phone: '+994553334455',
    },
    {
      slug: 'tebii-su-15l-600-ed-palet',
      title: 'Təbii su 1.5L 600 ədəd palet',
      store: 'Gəncə Market Təchizatı',
      storeSlug: 'ganca-market-techizati',
      city: 'Gəncə',
      category: 'Su və mineral sular',
      categorySlug: 'qida-ve-icki',
      price: '0.45 AZN',
      priceTiers: [
        { qty: '1+ palet', price: '0.45 AZN' },
        { qty: '10+ palet', price: '0.41 AZN' },
      ],
      minOrder: 'Min: 1 palet',
      badge: 'Stokda var',
      imageUrl: themedImage('qida-ve-icki', 3),
      imageAlt: 'Topdan su paleti',
      whatsappNumber: '+994553334455',
      phone: '+994553334455',
    },
    {
      slug: 'qulaqliq-kabel-dest-200-komplekt',
      title: 'Qulaqlıq + kabel dəsti 200 komplekt',
      store: 'Bakı Elektronik Bazarı',
      storeSlug: 'baku-elektronik-bazari',
      city: 'Bakı',
      category: 'Audio avadanlıqlar',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: '3.60 AZN',
      priceTiers: [
        { qty: '200+ komplekt', price: '3.60 AZN' },
        { qty: '600+ komplekt', price: '3.10 AZN' },
      ],
      minOrder: 'Min: 200 komplekt',
      badge: 'Yeni',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 2),
      imageAlt: 'Topdan audio aksesuar dəsti',
      whatsappNumber: '+994704445566',
      phone: '+994704445566',
    },
    {
      slug: 'telefon-cib-aksesuarlari-mix-500',
      title: 'Telefon cib aksesuarları mix 500 ədəd',
      store: 'Bakı Elektronik Bazarı',
      storeSlug: 'baku-elektronik-bazari',
      city: 'Bakı',
      category: 'Telefon aksesuarları',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: '1.80 AZN',
      priceTiers: [
        { qty: '500+ ədəd', price: '1.80 AZN' },
        { qty: '1500+ ədəd', price: '1.55 AZN' },
      ],
      minOrder: 'Min: 500 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 0),
      imageAlt: 'Topdan telefon aksesuarları',
      whatsappNumber: '+994704445566',
      phone: '+994704445566',
    },
    {
      slug: 'kisi-koynekleri-partiya-250',
      title: 'Kişi köynəkləri partiya 250 ədəd',
      store: 'Sumqayıt Tekstil Emalı',
      storeSlug: 'sumqayit-tekstil-emal',
      city: 'Sumqayıt',
      category: 'Kişi geyimləri',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '7.20 AZN',
      priceTiers: [
        { qty: '250+ ədəd', price: '7.20 AZN' },
        { qty: '700+ ədəd', price: '6.50 AZN' },
      ],
      minOrder: 'Min: 250 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 3),
      imageAlt: 'Topdan kişi köynək partiyası',
      whatsappNumber: '+994556667788',
      phone: '+994556667788',
    },
    {
      slug: 'qadin-sallari-mix-180',
      title: 'Qadın şalları mix 180 ədəd',
      store: 'Baku Tekstil MMC',
      storeSlug: 'baku-tekstil-mmc',
      city: 'Bakı',
      category: 'Qadın geyimləri',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '2.30 AZN',
      priceTiers: [
        { qty: '180+ ədəd', price: '2.30 AZN' },
        { qty: '600+ ədəd', price: '1.95 AZN' },
      ],
      minOrder: 'Min: 180 ədəd',
      badge: 'Yeni',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 1),
      imageAlt: 'Topdan qadın şalı partiyası',
      whatsappNumber: '+994501234567',
      phone: '+994501234567',
    },
    {
      slug: 'usaq-trikotaj-komplekt-300',
      title: 'Uşaq trikotaj komplektləri 300 dəst',
      store: 'Sumqayıt Tekstil Emalı',
      storeSlug: 'sumqayit-tekstil-emal',
      city: 'Sumqayıt',
      category: 'Uşaq geyimləri',
      categorySlug: 'geyim-ayaqqabi-ve-tekstil',
      price: '5.60 AZN',
      priceTiers: [
        { qty: '300+ dəst', price: '5.60 AZN' },
        { qty: '900+ dəst', price: '4.90 AZN' },
      ],
      minOrder: 'Min: 300 dəst',
      badge: 'Top satıcı',
      imageUrl: themedImage('geyim-ayaqqabi-ve-tekstil', 0),
      imageAlt: 'Topdan uşaq trikotaj komplekti',
      whatsappNumber: '+994556667788',
      phone: '+994556667788',
    },
    {
      slug: 'powerbank-10000mah-150-eded',
      title: 'Powerbank 10000mAh 150 ədəd',
      store: 'TechWholesale AZ',
      storeSlug: 'techwholesale-az',
      city: 'Bakı',
      category: 'Elektronika',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: '9.80 AZN',
      priceTiers: [
        { qty: '150+ ədəd', price: '9.80 AZN' },
        { qty: '500+ ədəd', price: '8.60 AZN' },
      ],
      minOrder: 'Min: 150 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 2),
      imageAlt: 'Topdan powerbank partiyası',
      whatsappNumber: '+994551112233',
      phone: '+994551112233',
    },
    {
      slug: 'telefon-ekran-qoruyucu-1000',
      title: 'Telefon ekran qoruyucu 1000 ədəd',
      store: 'Bakı Elektronik Bazarı',
      storeSlug: 'baku-elektronik-bazari',
      city: 'Bakı',
      category: 'Telefon aksesuarları',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: '0.55 AZN',
      priceTiers: [
        { qty: '1000+ ədəd', price: '0.55 AZN' },
        { qty: '3000+ ədəd', price: '0.44 AZN' },
      ],
      minOrder: 'Min: 1000 ədəd',
      badge: 'Top satıcı',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 1),
      imageAlt: 'Topdan ekran qoruyucu partiyası',
      whatsappNumber: '+994704445566',
      phone: '+994704445566',
    },
  );

  products.push(
    {
      slug: 'usb-kabel-desti-400',
      title: 'USB kabel dəsti 400 ədəd mix',
      store: 'TechWholesale AZ',
      storeSlug: 'techwholesale-az',
      city: 'Bakı',
      category: 'Elektronika',
      categorySlug: 'elektronika-ve-aksesuarlar',
      price: '1.20 AZN',
      priceTiers: [
        { qty: '400+ ədəd', price: '1.20 AZN' },
        { qty: '1200+ ədəd', price: '0.98 AZN' },
      ],
      minOrder: 'Min: 400 ədəd',
      badge: 'Yeni partiya',
      imageUrl: themedImage('elektronika-ve-aksesuarlar', 3),
      imageAlt: 'Topdan USB kabel dəsti',
      whatsappNumber: '+994551112233',
      phone: '+994551112233',
    },
    {
      slug: 'instants-qehve-24-qutu',
      title: 'İnstants qəhvə 100q 24 qutu partiya',
      store: 'Absheron Food Supply',
      storeSlug: 'absheron-food-supply',
      city: 'Bakı',
      category: 'Çay və qəhvə',
      categorySlug: 'qida-ve-icki',
      price: '34 AZN',
      priceTiers: [
        { qty: '24+ qutu', price: '34 AZN' },
        { qty: '72+ qutu', price: '30 AZN' },
      ],
      minOrder: 'Min: 24 qutu',
      badge: 'Stokda var',
      imageUrl: themedImage('qida-ve-icki', 2),
      imageAlt: 'Topdan qəhvə partiyası',
      whatsappNumber: '+994502101010',
      phone: '+994502101010',
    },
    {
      slug: 'konfet-mix-8kq-50-qutu',
      title: 'Konfet mix 8 kq 50 qutu topdan',
      store: 'Gəncə Market Təchizatı',
      storeSlug: 'ganca-market-techizati',
      city: 'Gəncə',
      category: 'Şokolad və konfetlər',
      categorySlug: 'qida-ve-icki',
      price: '26 AZN',
      priceTiers: [
        { qty: '50+ qutu', price: '26 AZN' },
        { qty: '150+ qutu', price: '23 AZN' },
      ],
      minOrder: 'Min: 50 qutu',
      badge: 'Yeni partiya',
      imageUrl: themedImage('qida-ve-icki', 0),
      imageAlt: 'Topdan konfet partiyası',
      whatsappNumber: '+994553334455',
      phone: '+994553334455',
    },
    {
      slug: 'div-yagi-5l-120-eded',
      title: 'Div yağı 5L 120 ədəd topdan',
      store: 'Lenkeran Meyvə Emalı',
      storeSlug: 'lenkeran-meyve-emali',
      city: 'Lənkəran',
      category: 'Yağlar və souslar',
      categorySlug: 'qida-ve-icki',
      price: '18.50 AZN',
      priceTiers: [
        { qty: '120+ ədəd', price: '18.50 AZN' },
        { qty: '360+ ədəd', price: '16.80 AZN' },
      ],
      minOrder: 'Min: 120 ədəd',
      badge: 'Stokda var',
      imageUrl: themedImage('qida-ve-icki', 3),
      imageAlt: 'Topdan yağ partiyası',
      whatsappNumber: '+994772223344',
      phone: '+994772223344',
    },
    {
      slug: 'sement-50kq-400-cu',
      title: 'Sement M400 50 kq 400 çu topdan',
      store: 'Salyan Təsərrüfat Malları',
      storeSlug: 'salyan-teserrufat-mallari',
      city: 'Mingəçevir',
      category: 'İnşaat materialları',
      categorySlug: 'tikinti-ve-temir',
      price: '11.40 AZN',
      priceTiers: [
        { qty: '400+ çu', price: '11.40 AZN' },
        { qty: '1200+ çu', price: '10.20 AZN' },
      ],
      minOrder: 'Min: 400 çu',
      badge: 'Stokda var',
      imageUrl: themedImage('tikinti-ve-temir', 2),
      imageAlt: 'Topdan sement partiyası',
      whatsappNumber: '+994777778899',
      phone: '+994777778899',
    },
    {
      slug: 'bag-alatlari-desti-90',
      title: 'Bağ alətləri dəsti 90 ədəd topdan',
      store: 'Salyan Təsərrüfat Malları',
      storeSlug: 'salyan-teserrufat-mallari',
      city: 'Mingəçevir',
      category: 'Təsərrüfat malları',
      categorySlug: 'tikinti-ve-temir',
      price: '6.70 AZN',
      priceTiers: [
        { qty: '90+ dəst', price: '6.70 AZN' },
        { qty: '300+ dəst', price: '5.90 AZN' },
      ],
      minOrder: 'Min: 90 dəst',
      badge: 'Yeni',
      imageUrl: themedImage('tikinti-ve-temir', 1),
      imageAlt: 'Topdan bağ alətləri dəsti',
      whatsappNumber: '+994777778899',
      phone: '+994777778899',
    },
  );

  return {
    products,
    stores: stores.map((store) => ({
      ...store,
      productCount: String(products.filter((product) => product.storeSlug === store.slug).length),
      views: '0',
      coverImageUrl: '/store-placeholder.svg',
    })),
  };
}
